import React from 'react';
import { BookOpen, Award, CheckCircle2 } from 'lucide-react';

export default function SummarySection({ title, summary }) {
  if (!summary || summary.length === 0) return null;

  return (
    <div className="w-full max-w-3xl rounded-2xl border border-obsidian-800 bg-obsidian-900/30 p-6 backdrop-blur-xl md:p-8 animate-scale-in mt-8">
      {/* Header section with decorative icon */}
      <div className="flex items-center space-x-3 mb-6">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-accent-cyan to-accent-violet text-white shadow-md shadow-accent-cyan/10">
          <BookOpen className="h-5 w-5" />
        </div>
        <h2 className="text-xl font-bold text-white tracking-tight md:text-2xl">
          Core Study Summary
        </h2>
      </div>

      {/* Main title generated by AI */}
      <div className="rounded-xl bg-gradient-to-r from-accent-violet/10 via-accent-cyan/5 to-transparent border border-accent-violet/20 p-5 mb-6">
        <span className="text-xs font-semibold uppercase tracking-wider text-accent-cyan">Topic Overview</span>
        <h3 className="text-2xl font-extrabold text-white mt-1 leading-tight tracking-tight">
          {title || 'Untitled Study Session'}
        </h3>
      </div>

      {/* Summary points list */}
      <div className="space-y-4 text-left">
        <span className="text-xs font-semibold uppercase tracking-wider text-obsidian-400">Key Takeaways</span>
        <ul className="space-y-3 mt-1">
          {summary.map((point, index) => (
            <li
              key={index}
              className="flex items-start space-x-3 rounded-lg border border-obsidian-800/40 bg-obsidian-900/10 p-4 transition-all hover:bg-obsidian-800/20 hover:border-obsidian-800"
            >
              <CheckCircle2 className="h-5 w-5 shrink-0 text-accent-cyan mt-0.5" />
              <span className="text-sm md:text-base text-obsidian-200 leading-relaxed">
                {point}
              </span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
