/**
 * Validates the study assistant JSON payload generated by AI.
 * Throws a descriptive error if the validation fails.
 * 
 * Target JSON schema:
 * {
 *   title: string,
 *   summary: string[],
 *   flashcards: Array<{ front: string, back: string }>,
 *   quiz: Array<{ question: string, options: string[], answer: string }>
 * }
 */
export function validateStudyData(data) {
  if (!data) {
    throw new Error('No data received from the study assistant engine.');
  }

  if (typeof data !== 'object' || Array.isArray(data)) {
    throw new Error('Invalid payload structure: Response is not a structured JSON object.');
  }

  // 1. Validate Title
  if (!data.title || typeof data.title !== 'string') {
    throw new Error('Validation failed: The study guide is missing a valid title.');
  }

  if (data.title.trim().length === 0) {
    throw new Error('Validation failed: The study guide title cannot be empty.');
  }

  // 2. Validate Summary
  if (!data.summary || !Array.isArray(data.summary)) {
    throw new Error('Validation failed: Key takeaways must be provided as a list (array).');
  }

  if (data.summary.length === 0) {
    throw new Error('Validation failed: The AI did not generate any summary points.');
  }

  data.summary.forEach((item, index) => {
    if (typeof item !== 'string' || item.trim().length === 0) {
      throw new Error(`Validation failed: Summary point at index ${index} must be a non-empty string.`);
    }
  });

  // 3. Validate Flashcards
  if (!data.flashcards || !Array.isArray(data.flashcards)) {
    throw new Error('Validation failed: Flashcards must be provided as a list (array).');
  }

  if (data.flashcards.length === 0) {
    throw new Error('Validation failed: The AI did not generate any flashcards.');
  }

  data.flashcards.forEach((card, index) => {
    if (typeof card !== 'object' || card === null || Array.isArray(card)) {
      throw new Error(`Validation failed: Flashcard at index ${index} must be a key-value object.`);
    }
    if (!card.front || typeof card.front !== 'string' || card.front.trim().length === 0) {
      throw new Error(`Validation failed: Flashcard at index ${index} is missing a valid front question/term.`);
    }
    if (!card.back || typeof card.back !== 'string' || card.back.trim().length === 0) {
      throw new Error(`Validation failed: Flashcard at index ${index} is missing a valid back answer/definition.`);
    }
  });

  // 4. Validate Quiz Questions
  if (!data.quiz || !Array.isArray(data.quiz)) {
    throw new Error('Validation failed: Quiz questions must be provided as a list (array).');
  }

  if (data.quiz.length === 0) {
    throw new Error('Validation failed: The AI did not generate any quiz questions.');
  }

  data.quiz.forEach((q, index) => {
    if (typeof q !== 'object' || q === null || Array.isArray(q)) {
      throw new Error(`Validation failed: Quiz item at index ${index} must be a key-value object.`);
    }
    if (!q.question || typeof q.question !== 'string' || q.question.trim().length === 0) {
      throw new Error(`Validation failed: Quiz question at index ${index} is missing the question text.`);
    }
    if (!q.options || !Array.isArray(q.options)) {
      throw new Error(`Validation failed: Quiz item at index ${index} is missing its multiple-choice options array.`);
    }
    if (q.options.length !== 4) {
      throw new Error(`Validation failed: Quiz item at index ${index} must contain exactly 4 multiple-choice options.`);
    }
    
    q.options.forEach((opt, oIdx) => {
      if (typeof opt !== 'string' || opt.trim().length === 0) {
        throw new Error(`Validation failed: Option at index ${oIdx} for question ${index} must be a non-empty string.`);
      }
    });

    if (!q.answer || typeof q.answer !== 'string' || q.answer.trim().length === 0) {
      throw new Error(`Validation failed: Quiz item at index ${index} is missing the correct answer key.`);
    }

    // Verify correct answer matches one of the options
    const optionMatches = q.options.some(opt => opt.trim() === q.answer.trim());
    if (!optionMatches) {
      throw new Error(`Validation failed: Quiz item at index ${index} specifies an answer ("${q.answer}") that does not match any of the provided options.`);
    }
  });

  return true;
}
